name: Build & Publish Container Image

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
      registry:
        required: false
        type: string
        default: ghcr.io
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: ./Dockerfile
      publish:
        required: false
        type: boolean
        default: ${{ github.ref_name == 'main' }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Get commit timestamp
        id: commit_timestamp
        run: echo "timestamp=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Log into Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f # v3

      - name: Build OCI Container Images
        uses: docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83 # v6
        env:
          SOURCE_DATE_EPOCH: ${{ steps.commit_timestamp.outputs.timestamp }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.publish }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
            ${{ inputs.registry }}/${{ inputs.name }}:latest
          cache-from: type=gha,scope=${{ inputs.name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.name }}
