name: Build & Publish Container Image

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
      registry:
        required: false
        type: string
        default: ghcr.io
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: ./Dockerfile
      publish:
        required: false
        type: boolean
        default: ${{ github.ref_name == 'main' }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Get commit timestamp
        id: commit_timestamp
        run: echo "timestamp=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Log into Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4.2.0
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4.1.0

      - name: Build OCI Container Images
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        env:
          SOURCE_DATE_EPOCH: ${{ steps.commit_timestamp.outputs.timestamp }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.publish }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
            ${{ inputs.registry }}/${{ inputs.name }}:latest
          cache-from: type=gha,scope=${{ inputs.name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.name }}
