name: Build & Publish Container Image

on:
  workflow_call:
    inputs:
      name:
        required: false
        type: string
        default: ${{ github.repository }}
      tag:
        required: false
        type: string
        default: ${{ github.sha }}
      registry:
        required: false
        type: string
        default: ghcr.io
      context:
        required: false
        type: string
        default: .
      file:
        required: false
        type: string
        default: ./Dockerfile
      publish:
        required: false
        type: boolean
        default: ${{ github.ref_name == 'main' }}

jobs:
  build:
    name: Build & Publish
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout Source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Get commit timestamp
        id: commit_timestamp
        run: echo "timestamp=$(git show -s --format=%ct ${{ github.sha }})" >> $GITHUB_OUTPUT

      - name: Log into Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4

      - name: Build OCI Container Images
        uses: docker/build-push-action@d08e5c354a6adb9ed34480a06d141179aa583294 # v7
        env:
          SOURCE_DATE_EPOCH: ${{ steps.commit_timestamp.outputs.timestamp }}
        with:
          context: ${{ inputs.context }}
          file: ${{ inputs.file }}
          push: ${{ inputs.publish }}
          tags: |
            ${{ inputs.registry }}/${{ inputs.name }}:${{ inputs.tag }}
            ${{ inputs.registry }}/${{ inputs.name }}:latest
          cache-from: type=gha,scope=${{ inputs.name }}
          cache-to: type=gha,mode=max,scope=${{ inputs.name }}
