name: Redocly Bundle Lint Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      redocly-version:
        required: false
        type: string
        default: ""
      openapi-file:
        required: false
        type: string
        default: "./openapi/openapi.yaml"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  bundle-lint:
    name: Redocly Bundle Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@84d5cca43835870d2d529688c279453ef718bd45 # main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Bundle APIs
        run: npx --yes @redocly/cli${{ inputs.redocly-version && format('@{0}', inputs.redocly-version) || '' }} bundle ${{ inputs.openapi-file }} --output bundled.yaml

      - name: Lint Check
        run: npx --yes @redocly/cli${{ inputs.redocly-version && format('@{0}', inputs.redocly-version) || '' }} lint bundled.yaml
