name: Redocly Bundle Lint Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      redocly-version:
        required: false
        type: string
        default: ""
      openapi-file:
        required: false
        type: string
        default: "./openapi/openapi.yaml"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  bundle-lint:
    name: Redocly Bundle Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@371fe3eeeda1e4467acf496bcba43f5feace1d6c # main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Bundle APIs
        run: npx --yes @redocly/cli${{ inputs.redocly-version && format('@{0}', inputs.redocly-version) || '' }} bundle ${{ inputs.openapi-file }} --output bundled.yaml

      - name: Lint Check
        run: npx --yes @redocly/cli${{ inputs.redocly-version && format('@{0}', inputs.redocly-version) || '' }} lint bundled.yaml
