name: Spectral Lint Check

on:
  workflow_call:
    inputs:
      node-version:
        required: false
        type: string
        default: ""
      spectral-version:
        required: false
        type: string
        default: ""
      file-glob:
        required: false
        type: string
        default: "./{openapi,asyncapi,arazzo}/*.{json,yml,yaml}"
      cache-dependency-manager:
        required: false
        type: string
        default: "npm"

jobs:
  lint:
    name: Spectral Lint Check
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - name: Checkout Source
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

      - name: Setup Node.js
        uses: bymbly/gha-workflows/.github/actions/setup-node@304a83e5b98adf7d78d9d0caa877273c961d54bc # main
        with:
          node-version: ${{ inputs.node-version }}
          cache: ${{ inputs.cache-dependency-manager }}

      - name: Install Dependencies
        run: npm ci

      - name: Lint Check
        run: npx --yes @stoplight/spectral-cli${{ inputs.spectral-version && format('@{0}', inputs.spectral-version) || '' }} lint --fail-severity warn ${{ inputs.file-glob }}
