name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@6e3cc8ac3f75fce3c1741aed7bdd86c589a6f866 # main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@6e3cc8ac3f75fce3c1741aed7bdd86c589a6f866 # main
