name: CI

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  prettier-format-check:
    name: Format Check
    uses: bymbly/gha-workflows/.github/workflows/prettier-format-check.yaml@807dab3c35f8d31b1cdaeee867e3ac990c3c0ec0 # main

  markdown-lint-check:
    name: Lint Check
    uses: bymbly/gha-workflows/.github/workflows/markdown-lint-check.yaml@807dab3c35f8d31b1cdaeee867e3ac990c3c0ec0 # main
